### PR TITLE
Allows using resources with ++plone++ in CSS definition URL of Galleria theme

### PR DESCRIPTION
**Pull request by wesleybl**
Previous version only replaced `++` if url contains `++resource++` causing Javascript regular expression error, when we had `++plone++`.

### CODE REVIEW

**Review by fredvd — APPROVED** [review]
Personally I'd stay on the safe side and add 'resource' or 'plone' to the regexp instead of replacing every single \+ occurrence, but LGTM otherwise.

**Comment by wesleybl** [comment]
@fredvd I'm afraid of having `++something++` in Plone, and giving an error. I already had `++resource++` and I bumped into `++plone++`. Do you know any others?

**Comment by fredvd** [comment]
Afaik we only have resource theme and plone

**Comment by wesleybl** [comment]
@fredvd I changed the code to replace only `\+\+plone\+\+` and `\+\+resource\+\+`.

**Comment by wesleybl** [comment]
Ops, forgot the theme.

**Comment by wesleybl** [comment]
Done theme

**Comment by fredvd** [comment]
Ok, lets wait until tomorrow morning for the other reviewers, but you added tests, fine to merge. Thanks!

**Pull request merged**
